### PR TITLE
Fix "copy" keyboard shortcut

### PR DESCRIPTION
**Pull request by vincentkam**
Fixes mtusnio/chinesedict#1

### CODE REVIEW

**Comment by vincentkam** [comment]
Updated logic so that "c" now copies all definitions in the pop-up, not just the first one

**Review by mtusnio — APPROVED** [review]

**Comment by mtusnio** [comment]
Very late on that, but will merge it in, test it out with some Canto dict updates and release

**Comment by mtusnio** [comment]
Thank you for the contribution, and apologies for being so late on that! Will try and get it out there in the next few weeks once I can get around to doing all the dict updates :)

**Comment by vincentkam** [comment]
Thank you @mtusnio :D Looking forward to it :)

**Pull request merged**
