### PR TITLE
Able to sound out selected character or phrase in Mandarin or Cantonese with a key press

### PR DESCRIPTION
**Pull request by eleehiga**

### CODE REVIEW

**Comment by eleehiga** [comment]
@mtusnio Was wondering if you could please take a look at my pull request here?

**Comment by mtusnio** [comment]
Hello @eleehiga ! Thank you for the PR and apologies for the delay! I have been quite bad at keeping track of PRs in this repo, and they happen rarely so I end up missing the notifications. 

I will have a look at it hopefully Saturday or Sunday to check out the functionality and make sure it all works ok, if that passes I see no reason not to merge it in :)

**Comment by mtusnio** [comment]
Works great on Windows, haven't had the chance to test it out on Linux! Any chance we can have a settings flag though to enable/disable tts? Feel like it would be a good thing to have a choice to disable to avoid overloading keyboard shortcuts

**Comment by eleehiga** [comment]
@mtusnio Just making sure, you mean to have this flag inside the code right?

**Comment by eleehiga** [comment]
@mtusnio Ah ok sounds good I am trying to have a checkbox in the contextMenus to enable or disable tts. But this might take a while more as I am having trouble with the message passing between background.js and content.js for `tts_en`.

**Comment by mtusnio** [comment]
If I get some time this Saturday I'll have a look myself how easy it might be!

**Comment by mtusnio** [comment]
Hey @eleehiga !

I had a look and I don't think you would need context menu options, I was more thinking of adding one to the options.html. I did a mock up of something that works, but haven't had a chance to properly test it out (no automated test, so all manual :().

I have moved creation of the utterance to the function itself as well.  Figured without TTS enabled you don't want to be calling the WebSpeech API :)

Have a look and let me know what you think

```
From 1d1fa611993a51a539d71e1a9600b023e7db97e4 Mon Sep 17 00:00:00 2001
From: Michal Tusnio <m.tusnio@gmail.com>
Date: Sat, 22 Jul 2023 13:53:30 +0100
Subject: [PATCH] Add TTS options

---
 background.js |  1 +
 content.js    | 19 +++++++++++--------
 js/options.js |  7 ++++++-
 options.html  |  8 ++++++++
 4 files changed, 26 insertions(+), 9 deletions(-)

diff --git a/background.js b/background.js
index c54542d..bd8f434 100644
--- a/background.js
+++ b/background.js
@@ -68,6 +68,7 @@ let zhongwenOptions = window.zhongwenOptions = {
     cantoneseEntriesEnabled: localStorage['cantoneseEntriesEnabled'] || 'yes',
     jyutpingEnabled: localStorage['jyutpingEnabled'] || 'yes',
     pinyinEnabled: localStorage['pinyinEnabled'] || 'yes',
+    ttsEnabled: localStorage['ttsEnabled'] || 'no'
 };
 
 function activateExtension(tabId, showHelp) {
diff --git a/content.js b/content.js
index ab0e9e4..db89ea2 100644
--- a/content.js
+++ b/content.js
@@ -86,8 +86,6 @@ let zwnj = /\u200c/g;
 // Initialize the speech synthesis object
 let synth = window.speechSynthesis;
 
-// Create a new utterance object
-let utterance = new SpeechSynthesisUtterance();
 
 function enableTab() {
     document.addEventListener('mousemove', onMouseMove);
@@ -151,12 +149,16 @@ function onKeyDown(keyDown) {
             copyToClipboard(getTextForClipboard());
             break;
 
-	case 69: // 'e', cantonese tts
-	    ttsCantonese(window.getSelection().toString());
-	    break;
+        case 69: // 'e', cantonese tts
+            if (config.ttsEnabled == 'yes') {
+                ttsCantonese(window.getSelection().toString());
+            }
+            break;
         case 87: // 'w', mandarin tts
-	    ttsMandarin(window.getSelection().toString());
-	    break;
+            if (config.ttsEnabled == 'yes') {
+                ttsMandarin(window.getSelection().toString());
+            }
+            break;
 
         case 66: // 'b'
         {
@@ -888,8 +890,9 @@ function copyToClipboard(data) {
 }
 
 function ttsAny(data, language) {
+    let utterance = new SpeechSynthesisUtterance();
     // Set the text to be spoken
-    utterance.text = data; 
+    utterance.text = data;
     // Set the language and voice for Mandarin
     utterance.lang = language;
     utterance.voice = synth.getVoices().find((voice) => voice.lang === language);
diff --git a/js/options.js b/js/options.js
index 12f3706..d07f083 100644
--- a/js/options.js
+++ b/js/options.js
@@ -45,6 +45,9 @@ function loadVals() {
 
     const pinyinEnabled = localStorage['pinyinEnabled'] || 'yes';
     document.querySelector('#pinyinEnabled').checked = pinyinEnabled === 'yes';
+
+    const ttsEnabled = localStorage['ttsEnabled'] || 'no';
+    document.querySelector('#ttsEnabled').checked = ttsEnabled === 'yes';
 }
 
 function setPopupColor(popupColor) {
@@ -117,7 +120,9 @@ window.addEventListener('load', () => {
 
     document.querySelector('#pinyinEnabled').addEventListener('change',
         (event) => setBooleanOption('pinyinEnabled', event.target.checked));
+
+    document.querySelector('#ttsEnabled').addEventListener('change',
+        (event) => setBooleanOption('ttsEnabled', event.target.checked));
 });
 
 loadVals();
-
diff --git a/options.html b/options.html
index 642a4b8..bc95f2e 100644
--- a/options.html
+++ b/options.html
@@ -174,6 +174,14 @@
             <label class="custom-control-label" for="skritterTLDcn">skritter.cn</label>
         </div>
     </div>
+
+    <div class="form-group mb-4">
+        <label>Enable text-to-speech</label>
+        <div class="custom-control custom-checkbox">
+            <input type="checkbox" class="custom-control-input" id="ttsEnabled" name="ttsEnabled">
+            <label class="custom-control-label" for="ttsEnabled">Enable text-to-speech</label>
+        </div>
+    </div>
 </div>
 <script src="js/options.js" type="text/javascript"></script>
 </body>
-- 
2.34.1
```

**Comment by eleehiga** [comment]
@mtusnio Thank you very much that works great. I apologize as I should have thought about adding to the options page with the enabling of TTS. Finally, I added you as a coauthor and as well updated the README.

**Comment by mtusnio** [comment]
Thank you! I will give it a bit of a test locally to make sure nothing got broken and will merge & release soon

**Comment by eleehiga** [comment]
@mtusnio Thank you for merging and releasing this new change!

**Comment by mtusnio** [comment]
No worries! It still is pending release, but I've submitted it for review :)

**Comment by mtusnio** [comment]
@eleehiga Just FYI, it's released as 1.1.0, I will create a new release here when I have a moment and add you in as a contributor in the release notes

**Comment by eleehiga** [comment]
@mtusnio Sounds good and thank you

**Pull request merged**
